### ISSUE TITLE
Error to load 

### ISSUE THREAD

**Issue by jarodium** [apilayer/html2pdf.it#68]
Hello
I have an issue loading a Cloudflare SSL protected website. 
I get the following error message:

> Unable to load the address (301): http://algarveedenproperties.com/***/criar_a4.php?id=730 fail

Loading https:// directly results in null.

Does still has to do with the underlying PhantomJS I have read in another issue? #61 
I have the link with SSL off ( in Cloudflare page rules ) and should be working, but since cloudflare seems to be issuing redirects anyway, is there any way we can reconfigure html2pdf.it to account for it?

**Comment by huichogil** [comment]
i have the same error 
how can i fix this

**Comment by fourroses666** [comment]
Looks like it needs paid version **if you use heroku**; https://www.heroku.com/dynos
